### ISSUE TITLE
zoomWindow reappears/stays when mouse leaves zoomPad quickly

### ISSUE THREAD

**Issue by timbeadle** [mrenzidev/jqzoom#2]
When moving the mouse quickly out from zoomPad onto the zoomWindow, the zoomWindow either stays in place, or fades out then in again quickly.

I've noticed the same behaviour (without the fades) on the examples on the main site:
http://www.mind-projects.it/projects/jqzoom/demos.php#demo6

Could it be due to event bubbling, as the zoomWindow is a child element of the original element that the jqzoom behaviour is attached to?

**Comment by bitsmanent** [comment]
That's due to the fact that JQZoom don't call .stop() before .fadeIn()/.fadeOut().
Unlucky, changing the relevant code to this.node.stop().fadein() doesn't works. I'm looking for a workaround.

**Comment by bitsmanent** [comment]
Okay, I fixed it. You can try this:

https://github.com/clamiax/jqzoom/blob/master/js/jquery.jqzoom-core.js

Hope this helps.
